var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                            xx  ",
   "  xx                                      o o                                x  ",
   "  x                     o                                                    x  ",
   "  x                                      xxxxx                             o x  ",
   "  x          xxxx       o                                                    x  ",
   "  x  @                                                           xxxxx       x  ",
   "  xxxxxxxxxx$$$$$$xxxx!!!!xxxxx$$$xxxxxx$$$$$$$xxxxxxxxxxxxxxxxxxx   xxxxxxxxx  ",
   "                              xxxxx     xxxxxxx                                 ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                            xx  ",
   "  xx                                                                         x  ",
   "  x                                                                          x  ",
   "  x                                                                o         x  ",
   "  x           o         o       o          o                                 x  ",
   "  x  @                                                           xxxxx       x  ",
   "  xxxxxxxxxx$$$$$$xxxx!!!!xxxxx$$$xxxxxx$$$$$$$xxxxxxxxxxxxxxxxxxx   xxxxxxxxx  ",
   "                              xxxxx     xxxxxxx                                 ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                        ",
   "                                                                        ",
   "                                                                        ",
   "                                                                        ",
   " 																		",
   "                                                                        ",
   "                                                                        ",
   "                              o                                          ",
   "                            xxxx                                        ",
   "                                                                        ",
   "                                                                        ",
   "                      xxx    xx    xxx                                  ",
   "                         x        x                                     ",
   "                         x        x                                     ",
   "             xxx          xx    xx          xxx                         ",
   "              x                             x                           ",
   "              x                             x                           ",
   "              x           xxxxxxxx          x                           ",
   "             xx                   = = = =   x                           ",
   "              x                             x                           ",
   "              x                             x                           ",
   "              x   xxxxxxx         xxxxxxx   x                           ",
   "             xx                             xx                          ",
   "              x = = = =                     x                           ",
   "              x             xxx              x                          ",
   "              x                             x                           ",
   "             xx           xx!!!xx           xx                          ",
   "              x             xxx             x                           ",
   "              x                             x                           ",
   "              xxx      xxx   x   xxx      xxx                           ",
   "              x          x!!!!!!!x          x                           ",
   "              x           x!!!!!x           x                           ",
   "             xx   xxxxxxxxxxxxxxxxxxxxxxx   xx                          ",
   "              x        v    !x!     v       x                           ",
   "              x            xxxxx            x                           ",
   "              x    xxx       !        xxxxxxx                           ",
   "              x              !              x                           ",
   "             xxx             !             xxx                          ",
   "              x              !    xxx       x                           ",
   "             xxxxxx          !   x!!!x      x                           ",
   "                      xxx         xxx       x                           ",
   "                       x    xxx             x                           ",
   "                             xxxxxxxxxxxxx                           x  ",
   "         @                   x           x                           x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx          xxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["																											                                                    ",
   "		xx	   xx    xxxx    xx    xx           xx           xx    xxx  xxx     x   xx  xx  xx                ",
   "		 xx   xx    xx  xx   xx    xx           xx           xx    xxx  xxxx    x   xx  xx  xx                ",
   "		  xx xx    xx    xx  xx    xx           xx     x     xx    xxx  xx xx   x   xx  xx  xx                ",
   "		   xxx     xx    xx  xx    xx            xx   xxx   xx     xxx  xx  xx  x   xx  xx  xx                ",
   "		   xxx     xx    xx  xx    xx             xx xx xx xx      xxx  xx   xx x   xx  xx  xx                ",
   "		   xxx      xx  xx    xx  xx               xxxx xxxx       xxx  xx    xxx                             ",
   "   @	   xxx       xxxx      xxxx                 xx   xx        xxx  xx     xx   xx  xx  xx              ",
   " xxxxx																										                                                ",
   "  xxx																									                                                 	  ",
   "   x																										                                                  ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
];
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
